/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as DashboardWhatsappRouteImport } from './routes/dashboard.whatsapp'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardFacebookRouteImport } from './routes/dashboard.facebook'
import { Route as DashboardControlRouteImport } from './routes/dashboard.control'
import { Route as DashboardBulkRouteImport } from './routes/dashboard.bulk'
import { Route as DashboardActivityRouteImport } from './routes/dashboard.activity'
import { Route as AdminWhatsappRouteImport } from './routes/admin.whatsapp'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSecurityRouteImport } from './routes/admin.security'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminJobsRouteImport } from './routes/admin.jobs'
import { Route as AdminFacebookRouteImport } from './routes/admin.facebook'
import { Route as AdminAiRouteImport } from './routes/admin.ai'
import { Route as DashboardWhatsappSettingsRouteImport } from './routes/dashboard.whatsapp.settings'
import { Route as DashboardWhatsappInboxRouteImport } from './routes/dashboard.whatsapp.inbox'
import { Route as DashboardWhatsappBotRouteImport } from './routes/dashboard.whatsapp.bot'
import { Route as DashboardWhatsappAccountsRouteImport } from './routes/dashboard.whatsapp.accounts'
import { Route as DashboardFacebookTemplatesRouteImport } from './routes/dashboard.facebook.templates'
import { Route as DashboardFacebookStatusRouteImport } from './routes/dashboard.facebook.status'
import { Route as DashboardFacebookMessagesRouteImport } from './routes/dashboard.facebook.messages'
import { Route as DashboardFacebookMediaRouteImport } from './routes/dashboard.facebook.media'
import { Route as DashboardFacebookJobsRouteImport } from './routes/dashboard.facebook.jobs'
import { Route as DashboardFacebookInsightsRouteImport } from './routes/dashboard.facebook.insights'
import { Route as DashboardFacebookHistoryRouteImport } from './routes/dashboard.facebook.history'
import { Route as DashboardFacebookGroupsRouteImport } from './routes/dashboard.facebook.groups'
import { Route as DashboardFacebookCampaignsRouteImport } from './routes/dashboard.facebook.campaigns'
import { Route as DashboardFacebookBotRouteImport } from './routes/dashboard.facebook.bot'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as DashboardFacebookCampaignsNewRouteImport } from './routes/dashboard.facebook.campaigns.new'
import { Route as DashboardFacebookCampaignsIdRouteImport } from './routes/dashboard.facebook.campaigns.$id'
import { Route as ApiPublicWaWebhookRouteImport } from './routes/api/public/wa/webhook'
import { Route as ApiPublicHooksProcessBulkJobsRouteImport } from './routes/api/public/hooks/process-bulk-jobs'
import { Route as ApiPublicBotNextJobRouteImport } from './routes/api/public/bot/next-job'
import { Route as ApiPublicBotJobUpdateRouteImport } from './routes/api/public/bot/job-update'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWhatsappRoute = DashboardWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFacebookRoute = DashboardFacebookRouteImport.update({
  id: '/facebook',
  path: '/facebook',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardControlRoute = DashboardControlRouteImport.update({
  id: '/control',
  path: '/control',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBulkRoute = DashboardBulkRouteImport.update({
  id: '/bulk',
  path: '/bulk',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardActivityRoute = DashboardActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminWhatsappRoute = AdminWhatsappRouteImport.update({
  id: '/admin/whatsapp',
  path: '/admin/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/admin/security',
  path: '/admin/security',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/admin/logs',
  path: '/admin/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/admin/jobs',
  path: '/admin/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFacebookRoute = AdminFacebookRouteImport.update({
  id: '/admin/facebook',
  path: '/admin/facebook',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAiRoute = AdminAiRouteImport.update({
  id: '/admin/ai',
  path: '/admin/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWhatsappSettingsRoute =
  DashboardWhatsappSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardWhatsappRoute,
  } as any)
const DashboardWhatsappInboxRoute = DashboardWhatsappInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => DashboardWhatsappRoute,
} as any)
const DashboardWhatsappBotRoute = DashboardWhatsappBotRouteImport.update({
  id: '/bot',
  path: '/bot',
  getParentRoute: () => DashboardWhatsappRoute,
} as any)
const DashboardWhatsappAccountsRoute =
  DashboardWhatsappAccountsRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => DashboardWhatsappRoute,
  } as any)
const DashboardFacebookTemplatesRoute =
  DashboardFacebookTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => DashboardFacebookRoute,
  } as any)
const DashboardFacebookStatusRoute = DashboardFacebookStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => DashboardFacebookRoute,
} as any)
const DashboardFacebookMessagesRoute =
  DashboardFacebookMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => DashboardFacebookRoute,
  } as any)
const DashboardFacebookMediaRoute = DashboardFacebookMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => DashboardFacebookRoute,
} as any)
const DashboardFacebookJobsRoute = DashboardFacebookJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => DashboardFacebookRoute,
} as any)
const DashboardFacebookInsightsRoute =
  DashboardFacebookInsightsRouteImport.update({
    id: '/insights',
    path: '/insights',
    getParentRoute: () => DashboardFacebookRoute,
  } as any)
const DashboardFacebookHistoryRoute =
  DashboardFacebookHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => DashboardFacebookRoute,
  } as any)
const DashboardFacebookGroupsRoute = DashboardFacebookGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => DashboardFacebookRoute,
} as any)
const DashboardFacebookCampaignsRoute =
  DashboardFacebookCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => DashboardFacebookRoute,
  } as any)
const DashboardFacebookBotRoute = DashboardFacebookBotRouteImport.update({
  id: '/bot',
  path: '/bot',
  getParentRoute: () => DashboardFacebookRoute,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFacebookCampaignsNewRoute =
  DashboardFacebookCampaignsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => DashboardFacebookCampaignsRoute,
  } as any)
const DashboardFacebookCampaignsIdRoute =
  DashboardFacebookCampaignsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => DashboardFacebookCampaignsRoute,
  } as any)
const ApiPublicWaWebhookRoute = ApiPublicWaWebhookRouteImport.update({
  id: '/api/public/wa/webhook',
  path: '/api/public/wa/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksProcessBulkJobsRoute =
  ApiPublicHooksProcessBulkJobsRouteImport.update({
    id: '/api/public/hooks/process-bulk-jobs',
    path: '/api/public/hooks/process-bulk-jobs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBotNextJobRoute = ApiPublicBotNextJobRouteImport.update({
  id: '/api/public/bot/next-job',
  path: '/api/public/bot/next-job',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBotJobUpdateRoute = ApiPublicBotJobUpdateRouteImport.update({
  id: '/api/public/bot/job-update',
  path: '/api/public/bot/job-update',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/facebook': typeof AdminFacebookRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/bulk': typeof DashboardBulkRoute
  '/dashboard/control': typeof DashboardControlRoute
  '/dashboard/facebook': typeof DashboardFacebookRouteWithChildren
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/whatsapp': typeof DashboardWhatsappRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/dashboard/facebook/bot': typeof DashboardFacebookBotRoute
  '/dashboard/facebook/campaigns': typeof DashboardFacebookCampaignsRouteWithChildren
  '/dashboard/facebook/groups': typeof DashboardFacebookGroupsRoute
  '/dashboard/facebook/history': typeof DashboardFacebookHistoryRoute
  '/dashboard/facebook/insights': typeof DashboardFacebookInsightsRoute
  '/dashboard/facebook/jobs': typeof DashboardFacebookJobsRoute
  '/dashboard/facebook/media': typeof DashboardFacebookMediaRoute
  '/dashboard/facebook/messages': typeof DashboardFacebookMessagesRoute
  '/dashboard/facebook/status': typeof DashboardFacebookStatusRoute
  '/dashboard/facebook/templates': typeof DashboardFacebookTemplatesRoute
  '/dashboard/whatsapp/accounts': typeof DashboardWhatsappAccountsRoute
  '/dashboard/whatsapp/bot': typeof DashboardWhatsappBotRoute
  '/dashboard/whatsapp/inbox': typeof DashboardWhatsappInboxRoute
  '/dashboard/whatsapp/settings': typeof DashboardWhatsappSettingsRoute
  '/api/public/bot/job-update': typeof ApiPublicBotJobUpdateRoute
  '/api/public/bot/next-job': typeof ApiPublicBotNextJobRoute
  '/api/public/hooks/process-bulk-jobs': typeof ApiPublicHooksProcessBulkJobsRoute
  '/api/public/wa/webhook': typeof ApiPublicWaWebhookRoute
  '/dashboard/facebook/campaigns/$id': typeof DashboardFacebookCampaignsIdRoute
  '/dashboard/facebook/campaigns/new': typeof DashboardFacebookCampaignsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/facebook': typeof AdminFacebookRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/bulk': typeof DashboardBulkRoute
  '/dashboard/control': typeof DashboardControlRoute
  '/dashboard/facebook': typeof DashboardFacebookRouteWithChildren
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/whatsapp': typeof DashboardWhatsappRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/dashboard/facebook/bot': typeof DashboardFacebookBotRoute
  '/dashboard/facebook/campaigns': typeof DashboardFacebookCampaignsRouteWithChildren
  '/dashboard/facebook/groups': typeof DashboardFacebookGroupsRoute
  '/dashboard/facebook/history': typeof DashboardFacebookHistoryRoute
  '/dashboard/facebook/insights': typeof DashboardFacebookInsightsRoute
  '/dashboard/facebook/jobs': typeof DashboardFacebookJobsRoute
  '/dashboard/facebook/media': typeof DashboardFacebookMediaRoute
  '/dashboard/facebook/messages': typeof DashboardFacebookMessagesRoute
  '/dashboard/facebook/status': typeof DashboardFacebookStatusRoute
  '/dashboard/facebook/templates': typeof DashboardFacebookTemplatesRoute
  '/dashboard/whatsapp/accounts': typeof DashboardWhatsappAccountsRoute
  '/dashboard/whatsapp/bot': typeof DashboardWhatsappBotRoute
  '/dashboard/whatsapp/inbox': typeof DashboardWhatsappInboxRoute
  '/dashboard/whatsapp/settings': typeof DashboardWhatsappSettingsRoute
  '/api/public/bot/job-update': typeof ApiPublicBotJobUpdateRoute
  '/api/public/bot/next-job': typeof ApiPublicBotNextJobRoute
  '/api/public/hooks/process-bulk-jobs': typeof ApiPublicHooksProcessBulkJobsRoute
  '/api/public/wa/webhook': typeof ApiPublicWaWebhookRoute
  '/dashboard/facebook/campaigns/$id': typeof DashboardFacebookCampaignsIdRoute
  '/dashboard/facebook/campaigns/new': typeof DashboardFacebookCampaignsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/facebook': typeof AdminFacebookRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/bulk': typeof DashboardBulkRoute
  '/dashboard/control': typeof DashboardControlRoute
  '/dashboard/facebook': typeof DashboardFacebookRouteWithChildren
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/whatsapp': typeof DashboardWhatsappRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/dashboard/facebook/bot': typeof DashboardFacebookBotRoute
  '/dashboard/facebook/campaigns': typeof DashboardFacebookCampaignsRouteWithChildren
  '/dashboard/facebook/groups': typeof DashboardFacebookGroupsRoute
  '/dashboard/facebook/history': typeof DashboardFacebookHistoryRoute
  '/dashboard/facebook/insights': typeof DashboardFacebookInsightsRoute
  '/dashboard/facebook/jobs': typeof DashboardFacebookJobsRoute
  '/dashboard/facebook/media': typeof DashboardFacebookMediaRoute
  '/dashboard/facebook/messages': typeof DashboardFacebookMessagesRoute
  '/dashboard/facebook/status': typeof DashboardFacebookStatusRoute
  '/dashboard/facebook/templates': typeof DashboardFacebookTemplatesRoute
  '/dashboard/whatsapp/accounts': typeof DashboardWhatsappAccountsRoute
  '/dashboard/whatsapp/bot': typeof DashboardWhatsappBotRoute
  '/dashboard/whatsapp/inbox': typeof DashboardWhatsappInboxRoute
  '/dashboard/whatsapp/settings': typeof DashboardWhatsappSettingsRoute
  '/api/public/bot/job-update': typeof ApiPublicBotJobUpdateRoute
  '/api/public/bot/next-job': typeof ApiPublicBotNextJobRoute
  '/api/public/hooks/process-bulk-jobs': typeof ApiPublicHooksProcessBulkJobsRoute
  '/api/public/wa/webhook': typeof ApiPublicWaWebhookRoute
  '/dashboard/facebook/campaigns/$id': typeof DashboardFacebookCampaignsIdRoute
  '/dashboard/facebook/campaigns/new': typeof DashboardFacebookCampaignsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin/ai'
    | '/admin/facebook'
    | '/admin/jobs'
    | '/admin/logs'
    | '/admin/notifications'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/whatsapp'
    | '/dashboard/activity'
    | '/dashboard/bulk'
    | '/dashboard/control'
    | '/dashboard/facebook'
    | '/dashboard/profile'
    | '/dashboard/whatsapp'
    | '/admin/'
    | '/api/public/health'
    | '/dashboard/facebook/bot'
    | '/dashboard/facebook/campaigns'
    | '/dashboard/facebook/groups'
    | '/dashboard/facebook/history'
    | '/dashboard/facebook/insights'
    | '/dashboard/facebook/jobs'
    | '/dashboard/facebook/media'
    | '/dashboard/facebook/messages'
    | '/dashboard/facebook/status'
    | '/dashboard/facebook/templates'
    | '/dashboard/whatsapp/accounts'
    | '/dashboard/whatsapp/bot'
    | '/dashboard/whatsapp/inbox'
    | '/dashboard/whatsapp/settings'
    | '/api/public/bot/job-update'
    | '/api/public/bot/next-job'
    | '/api/public/hooks/process-bulk-jobs'
    | '/api/public/wa/webhook'
    | '/dashboard/facebook/campaigns/$id'
    | '/dashboard/facebook/campaigns/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin/ai'
    | '/admin/facebook'
    | '/admin/jobs'
    | '/admin/logs'
    | '/admin/notifications'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/whatsapp'
    | '/dashboard/activity'
    | '/dashboard/bulk'
    | '/dashboard/control'
    | '/dashboard/facebook'
    | '/dashboard/profile'
    | '/dashboard/whatsapp'
    | '/admin'
    | '/api/public/health'
    | '/dashboard/facebook/bot'
    | '/dashboard/facebook/campaigns'
    | '/dashboard/facebook/groups'
    | '/dashboard/facebook/history'
    | '/dashboard/facebook/insights'
    | '/dashboard/facebook/jobs'
    | '/dashboard/facebook/media'
    | '/dashboard/facebook/messages'
    | '/dashboard/facebook/status'
    | '/dashboard/facebook/templates'
    | '/dashboard/whatsapp/accounts'
    | '/dashboard/whatsapp/bot'
    | '/dashboard/whatsapp/inbox'
    | '/dashboard/whatsapp/settings'
    | '/api/public/bot/job-update'
    | '/api/public/bot/next-job'
    | '/api/public/hooks/process-bulk-jobs'
    | '/api/public/wa/webhook'
    | '/dashboard/facebook/campaigns/$id'
    | '/dashboard/facebook/campaigns/new'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin/ai'
    | '/admin/facebook'
    | '/admin/jobs'
    | '/admin/logs'
    | '/admin/notifications'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/whatsapp'
    | '/dashboard/activity'
    | '/dashboard/bulk'
    | '/dashboard/control'
    | '/dashboard/facebook'
    | '/dashboard/profile'
    | '/dashboard/whatsapp'
    | '/admin/'
    | '/api/public/health'
    | '/dashboard/facebook/bot'
    | '/dashboard/facebook/campaigns'
    | '/dashboard/facebook/groups'
    | '/dashboard/facebook/history'
    | '/dashboard/facebook/insights'
    | '/dashboard/facebook/jobs'
    | '/dashboard/facebook/media'
    | '/dashboard/facebook/messages'
    | '/dashboard/facebook/status'
    | '/dashboard/facebook/templates'
    | '/dashboard/whatsapp/accounts'
    | '/dashboard/whatsapp/bot'
    | '/dashboard/whatsapp/inbox'
    | '/dashboard/whatsapp/settings'
    | '/api/public/bot/job-update'
    | '/api/public/bot/next-job'
    | '/api/public/hooks/process-bulk-jobs'
    | '/api/public/wa/webhook'
    | '/dashboard/facebook/campaigns/$id'
    | '/dashboard/facebook/campaigns/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  AdminAiRoute: typeof AdminAiRoute
  AdminFacebookRoute: typeof AdminFacebookRoute
  AdminJobsRoute: typeof AdminJobsRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWhatsappRoute: typeof AdminWhatsappRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicBotJobUpdateRoute: typeof ApiPublicBotJobUpdateRoute
  ApiPublicBotNextJobRoute: typeof ApiPublicBotNextJobRoute
  ApiPublicHooksProcessBulkJobsRoute: typeof ApiPublicHooksProcessBulkJobsRoute
  ApiPublicWaWebhookRoute: typeof ApiPublicWaWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/whatsapp': {
      id: '/dashboard/whatsapp'
      path: '/whatsapp'
      fullPath: '/dashboard/whatsapp'
      preLoaderRoute: typeof DashboardWhatsappRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/facebook': {
      id: '/dashboard/facebook'
      path: '/facebook'
      fullPath: '/dashboard/facebook'
      preLoaderRoute: typeof DashboardFacebookRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/control': {
      id: '/dashboard/control'
      path: '/control'
      fullPath: '/dashboard/control'
      preLoaderRoute: typeof DashboardControlRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bulk': {
      id: '/dashboard/bulk'
      path: '/bulk'
      fullPath: '/dashboard/bulk'
      preLoaderRoute: typeof DashboardBulkRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/activity': {
      id: '/dashboard/activity'
      path: '/activity'
      fullPath: '/dashboard/activity'
      preLoaderRoute: typeof DashboardActivityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/whatsapp': {
      id: '/admin/whatsapp'
      path: '/admin/whatsapp'
      fullPath: '/admin/whatsapp'
      preLoaderRoute: typeof AdminWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/admin/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/admin/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/admin/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/facebook': {
      id: '/admin/facebook'
      path: '/admin/facebook'
      fullPath: '/admin/facebook'
      preLoaderRoute: typeof AdminFacebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ai': {
      id: '/admin/ai'
      path: '/admin/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AdminAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/whatsapp/settings': {
      id: '/dashboard/whatsapp/settings'
      path: '/settings'
      fullPath: '/dashboard/whatsapp/settings'
      preLoaderRoute: typeof DashboardWhatsappSettingsRouteImport
      parentRoute: typeof DashboardWhatsappRoute
    }
    '/dashboard/whatsapp/inbox': {
      id: '/dashboard/whatsapp/inbox'
      path: '/inbox'
      fullPath: '/dashboard/whatsapp/inbox'
      preLoaderRoute: typeof DashboardWhatsappInboxRouteImport
      parentRoute: typeof DashboardWhatsappRoute
    }
    '/dashboard/whatsapp/bot': {
      id: '/dashboard/whatsapp/bot'
      path: '/bot'
      fullPath: '/dashboard/whatsapp/bot'
      preLoaderRoute: typeof DashboardWhatsappBotRouteImport
      parentRoute: typeof DashboardWhatsappRoute
    }
    '/dashboard/whatsapp/accounts': {
      id: '/dashboard/whatsapp/accounts'
      path: '/accounts'
      fullPath: '/dashboard/whatsapp/accounts'
      preLoaderRoute: typeof DashboardWhatsappAccountsRouteImport
      parentRoute: typeof DashboardWhatsappRoute
    }
    '/dashboard/facebook/templates': {
      id: '/dashboard/facebook/templates'
      path: '/templates'
      fullPath: '/dashboard/facebook/templates'
      preLoaderRoute: typeof DashboardFacebookTemplatesRouteImport
      parentRoute: typeof DashboardFacebookRoute
    }
    '/dashboard/facebook/status': {
      id: '/dashboard/facebook/status'
      path: '/status'
      fullPath: '/dashboard/facebook/status'
      preLoaderRoute: typeof DashboardFacebookStatusRouteImport
      parentRoute: typeof DashboardFacebookRoute
    }
    '/dashboard/facebook/messages': {
      id: '/dashboard/facebook/messages'
      path: '/messages'
      fullPath: '/dashboard/facebook/messages'
      preLoaderRoute: typeof DashboardFacebookMessagesRouteImport
      parentRoute: typeof DashboardFacebookRoute
    }
    '/dashboard/facebook/media': {
      id: '/dashboard/facebook/media'
      path: '/media'
      fullPath: '/dashboard/facebook/media'
      preLoaderRoute: typeof DashboardFacebookMediaRouteImport
      parentRoute: typeof DashboardFacebookRoute
    }
    '/dashboard/facebook/jobs': {
      id: '/dashboard/facebook/jobs'
      path: '/jobs'
      fullPath: '/dashboard/facebook/jobs'
      preLoaderRoute: typeof DashboardFacebookJobsRouteImport
      parentRoute: typeof DashboardFacebookRoute
    }
    '/dashboard/facebook/insights': {
      id: '/dashboard/facebook/insights'
      path: '/insights'
      fullPath: '/dashboard/facebook/insights'
      preLoaderRoute: typeof DashboardFacebookInsightsRouteImport
      parentRoute: typeof DashboardFacebookRoute
    }
    '/dashboard/facebook/history': {
      id: '/dashboard/facebook/history'
      path: '/history'
      fullPath: '/dashboard/facebook/history'
      preLoaderRoute: typeof DashboardFacebookHistoryRouteImport
      parentRoute: typeof DashboardFacebookRoute
    }
    '/dashboard/facebook/groups': {
      id: '/dashboard/facebook/groups'
      path: '/groups'
      fullPath: '/dashboard/facebook/groups'
      preLoaderRoute: typeof DashboardFacebookGroupsRouteImport
      parentRoute: typeof DashboardFacebookRoute
    }
    '/dashboard/facebook/campaigns': {
      id: '/dashboard/facebook/campaigns'
      path: '/campaigns'
      fullPath: '/dashboard/facebook/campaigns'
      preLoaderRoute: typeof DashboardFacebookCampaignsRouteImport
      parentRoute: typeof DashboardFacebookRoute
    }
    '/dashboard/facebook/bot': {
      id: '/dashboard/facebook/bot'
      path: '/bot'
      fullPath: '/dashboard/facebook/bot'
      preLoaderRoute: typeof DashboardFacebookBotRouteImport
      parentRoute: typeof DashboardFacebookRoute
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/facebook/campaigns/new': {
      id: '/dashboard/facebook/campaigns/new'
      path: '/new'
      fullPath: '/dashboard/facebook/campaigns/new'
      preLoaderRoute: typeof DashboardFacebookCampaignsNewRouteImport
      parentRoute: typeof DashboardFacebookCampaignsRoute
    }
    '/dashboard/facebook/campaigns/$id': {
      id: '/dashboard/facebook/campaigns/$id'
      path: '/$id'
      fullPath: '/dashboard/facebook/campaigns/$id'
      preLoaderRoute: typeof DashboardFacebookCampaignsIdRouteImport
      parentRoute: typeof DashboardFacebookCampaignsRoute
    }
    '/api/public/wa/webhook': {
      id: '/api/public/wa/webhook'
      path: '/api/public/wa/webhook'
      fullPath: '/api/public/wa/webhook'
      preLoaderRoute: typeof ApiPublicWaWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-bulk-jobs': {
      id: '/api/public/hooks/process-bulk-jobs'
      path: '/api/public/hooks/process-bulk-jobs'
      fullPath: '/api/public/hooks/process-bulk-jobs'
      preLoaderRoute: typeof ApiPublicHooksProcessBulkJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/next-job': {
      id: '/api/public/bot/next-job'
      path: '/api/public/bot/next-job'
      fullPath: '/api/public/bot/next-job'
      preLoaderRoute: typeof ApiPublicBotNextJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/job-update': {
      id: '/api/public/bot/job-update'
      path: '/api/public/bot/job-update'
      fullPath: '/api/public/bot/job-update'
      preLoaderRoute: typeof ApiPublicBotJobUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardFacebookCampaignsRouteChildren {
  DashboardFacebookCampaignsIdRoute: typeof DashboardFacebookCampaignsIdRoute
  DashboardFacebookCampaignsNewRoute: typeof DashboardFacebookCampaignsNewRoute
}

const DashboardFacebookCampaignsRouteChildren: DashboardFacebookCampaignsRouteChildren =
  {
    DashboardFacebookCampaignsIdRoute: DashboardFacebookCampaignsIdRoute,
    DashboardFacebookCampaignsNewRoute: DashboardFacebookCampaignsNewRoute,
  }

const DashboardFacebookCampaignsRouteWithChildren =
  DashboardFacebookCampaignsRoute._addFileChildren(
    DashboardFacebookCampaignsRouteChildren,
  )

interface DashboardFacebookRouteChildren {
  DashboardFacebookBotRoute: typeof DashboardFacebookBotRoute
  DashboardFacebookCampaignsRoute: typeof DashboardFacebookCampaignsRouteWithChildren
  DashboardFacebookGroupsRoute: typeof DashboardFacebookGroupsRoute
  DashboardFacebookHistoryRoute: typeof DashboardFacebookHistoryRoute
  DashboardFacebookInsightsRoute: typeof DashboardFacebookInsightsRoute
  DashboardFacebookJobsRoute: typeof DashboardFacebookJobsRoute
  DashboardFacebookMediaRoute: typeof DashboardFacebookMediaRoute
  DashboardFacebookMessagesRoute: typeof DashboardFacebookMessagesRoute
  DashboardFacebookStatusRoute: typeof DashboardFacebookStatusRoute
  DashboardFacebookTemplatesRoute: typeof DashboardFacebookTemplatesRoute
}

const DashboardFacebookRouteChildren: DashboardFacebookRouteChildren = {
  DashboardFacebookBotRoute: DashboardFacebookBotRoute,
  DashboardFacebookCampaignsRoute: DashboardFacebookCampaignsRouteWithChildren,
  DashboardFacebookGroupsRoute: DashboardFacebookGroupsRoute,
  DashboardFacebookHistoryRoute: DashboardFacebookHistoryRoute,
  DashboardFacebookInsightsRoute: DashboardFacebookInsightsRoute,
  DashboardFacebookJobsRoute: DashboardFacebookJobsRoute,
  DashboardFacebookMediaRoute: DashboardFacebookMediaRoute,
  DashboardFacebookMessagesRoute: DashboardFacebookMessagesRoute,
  DashboardFacebookStatusRoute: DashboardFacebookStatusRoute,
  DashboardFacebookTemplatesRoute: DashboardFacebookTemplatesRoute,
}

const DashboardFacebookRouteWithChildren =
  DashboardFacebookRoute._addFileChildren(DashboardFacebookRouteChildren)

interface DashboardWhatsappRouteChildren {
  DashboardWhatsappAccountsRoute: typeof DashboardWhatsappAccountsRoute
  DashboardWhatsappBotRoute: typeof DashboardWhatsappBotRoute
  DashboardWhatsappInboxRoute: typeof DashboardWhatsappInboxRoute
  DashboardWhatsappSettingsRoute: typeof DashboardWhatsappSettingsRoute
}

const DashboardWhatsappRouteChildren: DashboardWhatsappRouteChildren = {
  DashboardWhatsappAccountsRoute: DashboardWhatsappAccountsRoute,
  DashboardWhatsappBotRoute: DashboardWhatsappBotRoute,
  DashboardWhatsappInboxRoute: DashboardWhatsappInboxRoute,
  DashboardWhatsappSettingsRoute: DashboardWhatsappSettingsRoute,
}

const DashboardWhatsappRouteWithChildren =
  DashboardWhatsappRoute._addFileChildren(DashboardWhatsappRouteChildren)

interface DashboardRouteChildren {
  DashboardActivityRoute: typeof DashboardActivityRoute
  DashboardBulkRoute: typeof DashboardBulkRoute
  DashboardControlRoute: typeof DashboardControlRoute
  DashboardFacebookRoute: typeof DashboardFacebookRouteWithChildren
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardWhatsappRoute: typeof DashboardWhatsappRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardActivityRoute: DashboardActivityRoute,
  DashboardBulkRoute: DashboardBulkRoute,
  DashboardControlRoute: DashboardControlRoute,
  DashboardFacebookRoute: DashboardFacebookRouteWithChildren,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardWhatsappRoute: DashboardWhatsappRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  AdminAiRoute: AdminAiRoute,
  AdminFacebookRoute: AdminFacebookRoute,
  AdminJobsRoute: AdminJobsRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWhatsappRoute: AdminWhatsappRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicBotJobUpdateRoute: ApiPublicBotJobUpdateRoute,
  ApiPublicBotNextJobRoute: ApiPublicBotNextJobRoute,
  ApiPublicHooksProcessBulkJobsRoute: ApiPublicHooksProcessBulkJobsRoute,
  ApiPublicWaWebhookRoute: ApiPublicWaWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
