-- ============================================================
-- TASK 13: WhatsApp Settings (Quick Replies + Webhooks + Business Hours)
-- ============================================================
-- (See applied migration for full SQL)
