name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - run: npm ci && npm run build
        env:
          VITE_SUPABASE_URL: ${{  secrets.VITE_SUPABASE_URL  }}
          VITE_SUPABASE_ANON_KEY: ${{  secrets.VITE_SUPABASE_ANON_KEY  }}

      - uses: easingthemes/ssh-deploy@v5
        with:
          SSH_PRIVATE_KEY: ${{  secrets.SSH_KEY  }}
          ARGS: "-avz --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{  secrets.VPS_HOST  }}
          REMOTE_USER: ${{  secrets.VPS_USER  }}
          TARGET: "/var/www/flowtix"
